// flow-typed signature: 8f86ccf9f832839c20ddb417d7cd6979
// flow-typed version: <<STUB>>/react-native-meteor_v^1.3.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-meteor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-meteor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-meteor/lib/ddp' {
  declare module.exports: any;
}

declare module 'react-native-meteor/lib/mongo-id' {
  declare module.exports: any;
}

declare module 'react-native-meteor/lib/queue' {
  declare module.exports: any;
}

declare module 'react-native-meteor/lib/Random' {
  declare module.exports: any;
}

declare module 'react-native-meteor/lib/socket' {
  declare module.exports: any;
}

declare module 'react-native-meteor/lib/utils' {
  declare module.exports: any;
}

declare module 'react-native-meteor/src/Call' {
  declare module.exports: any;
}

declare module 'react-native-meteor/src/Collection' {
  declare module.exports: any;
}

declare module 'react-native-meteor/src/CollectionFS/FSCollection' {
  declare module.exports: any;
}

declare module 'react-native-meteor/src/CollectionFS/FSCollectionImagesPreloader' {
  declare module.exports: any;
}

declare module 'react-native-meteor/src/CollectionFS/setProperties' {
  declare module.exports: any;
}

declare module 'react-native-meteor/src/components/ComplexListView' {
  declare module.exports: any;
}

declare module 'react-native-meteor/src/components/composeWithTracker' {
  declare module.exports: any;
}

declare module 'react-native-meteor/src/components/createContainer' {
  declare module.exports: any;
}

declare module 'react-native-meteor/src/components/ListView' {
  declare module.exports: any;
}

declare module 'react-native-meteor/src/components/MeteorDataManager' {
  declare module.exports: any;
}

declare module 'react-native-meteor/src/components/Mixin' {
  declare module.exports: any;
}

declare module 'react-native-meteor/src/components/ReactMeteorData' {
  declare module.exports: any;
}

declare module 'react-native-meteor/src/Data' {
  declare module.exports: any;
}

declare module 'react-native-meteor/src/Meteor' {
  declare module.exports: any;
}

declare module 'react-native-meteor/src/ReactiveDict' {
  declare module.exports: any;
}

declare module 'react-native-meteor/src/user/Accounts' {
  declare module.exports: any;
}

declare module 'react-native-meteor/src/user/User' {
  declare module.exports: any;
}

declare module 'react-native-meteor/test/lib/ddpShould' {
  declare module.exports: any;
}

declare module 'react-native-meteor/test/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-meteor/lib/ddp.js' {
  declare module.exports: $Exports<'react-native-meteor/lib/ddp'>;
}
declare module 'react-native-meteor/lib/mongo-id.js' {
  declare module.exports: $Exports<'react-native-meteor/lib/mongo-id'>;
}
declare module 'react-native-meteor/lib/queue.js' {
  declare module.exports: $Exports<'react-native-meteor/lib/queue'>;
}
declare module 'react-native-meteor/lib/Random.js' {
  declare module.exports: $Exports<'react-native-meteor/lib/Random'>;
}
declare module 'react-native-meteor/lib/socket.js' {
  declare module.exports: $Exports<'react-native-meteor/lib/socket'>;
}
declare module 'react-native-meteor/lib/utils.js' {
  declare module.exports: $Exports<'react-native-meteor/lib/utils'>;
}
declare module 'react-native-meteor/src/Call.js' {
  declare module.exports: $Exports<'react-native-meteor/src/Call'>;
}
declare module 'react-native-meteor/src/Collection.js' {
  declare module.exports: $Exports<'react-native-meteor/src/Collection'>;
}
declare module 'react-native-meteor/src/CollectionFS/FSCollection.js' {
  declare module.exports: $Exports<'react-native-meteor/src/CollectionFS/FSCollection'>;
}
declare module 'react-native-meteor/src/CollectionFS/FSCollectionImagesPreloader.js' {
  declare module.exports: $Exports<'react-native-meteor/src/CollectionFS/FSCollectionImagesPreloader'>;
}
declare module 'react-native-meteor/src/CollectionFS/setProperties.js' {
  declare module.exports: $Exports<'react-native-meteor/src/CollectionFS/setProperties'>;
}
declare module 'react-native-meteor/src/components/ComplexListView.js' {
  declare module.exports: $Exports<'react-native-meteor/src/components/ComplexListView'>;
}
declare module 'react-native-meteor/src/components/composeWithTracker.js' {
  declare module.exports: $Exports<'react-native-meteor/src/components/composeWithTracker'>;
}
declare module 'react-native-meteor/src/components/createContainer.js' {
  declare module.exports: $Exports<'react-native-meteor/src/components/createContainer'>;
}
declare module 'react-native-meteor/src/components/ListView.js' {
  declare module.exports: $Exports<'react-native-meteor/src/components/ListView'>;
}
declare module 'react-native-meteor/src/components/MeteorDataManager.js' {
  declare module.exports: $Exports<'react-native-meteor/src/components/MeteorDataManager'>;
}
declare module 'react-native-meteor/src/components/Mixin.js' {
  declare module.exports: $Exports<'react-native-meteor/src/components/Mixin'>;
}
declare module 'react-native-meteor/src/components/ReactMeteorData.js' {
  declare module.exports: $Exports<'react-native-meteor/src/components/ReactMeteorData'>;
}
declare module 'react-native-meteor/src/Data.js' {
  declare module.exports: $Exports<'react-native-meteor/src/Data'>;
}
declare module 'react-native-meteor/src/Meteor.js' {
  declare module.exports: $Exports<'react-native-meteor/src/Meteor'>;
}
declare module 'react-native-meteor/src/ReactiveDict.js' {
  declare module.exports: $Exports<'react-native-meteor/src/ReactiveDict'>;
}
declare module 'react-native-meteor/src/user/Accounts.js' {
  declare module.exports: $Exports<'react-native-meteor/src/user/Accounts'>;
}
declare module 'react-native-meteor/src/user/User.js' {
  declare module.exports: $Exports<'react-native-meteor/src/user/User'>;
}
declare module 'react-native-meteor/test/lib/ddpShould.js' {
  declare module.exports: $Exports<'react-native-meteor/test/lib/ddpShould'>;
}
declare module 'react-native-meteor/test/setup.js' {
  declare module.exports: $Exports<'react-native-meteor/test/setup'>;
}
